import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}




import { FaShoppingCart } from "react-icons/fa"
import { IoIosSearch } from "react-icons/io"
import { MdAccountCircle } from "react-icons/md"

export const Upper = () => {
  return (
    <div className="flex justify-center text-white bg-black">Sign up and get 20% off to your first order. Sign Up Now</div>
  )
}




export const Header = () => {
  return (
    <div><header className="text-black">
    <div className="container mx-auto flex flex-wrap p-10 flex-col md:flex-row">
      <a className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <span className="ml-14 w-{1000px} h-{2431px} top-{-1750px} left-{100px} size-7 gap-{32px}"><b>SHOP.CO</b></span>
      </a>
      <nav className="flex flex-wrap items-center text-base justify-center">
        <div className="ml-28 hover:text-gray-400-900">
          <select>
            <option>Shop</option>
            <option >T-shirt</option>
            </select></div>
        <div className="ml-11 hover:text-gray-400-900">On Sale</div>
        <div className="ml-11 hover:text-gray-400-900">New Arrivals</div>
        <div className="ml-11 hover:text-gray-400-900">Brands</div>
        </nav>
        
        
        <div className="flex ml-11">
          <IoIosSearch className="ml-3 text-gray-700 size-22 w-6px mt-1" / >
        <input type="text"  placeholder="Search for products..." className=""></input>
        </div>
        
        
        <FaShoppingCart className="ml-24 hrs" />
        <MdAccountCircle className="ml-6"/>
        </div>
    
  </header>
  </div>
  )
}




import { BiHorizontalCenter } from "react-icons/bi"
import { FaFacebook, FaInstagram } from "react-icons/fa"
import { IoLogoGithub } from "react-icons/io"
import { MdHorizontalSplit } from "react-icons/md"
import { TiSocialTwitter } from "react-icons/ti"
import { IoIosMail } from "react-icons/io";

export const Footer = () => (
  <div>
    <footer className="text-gray-600 body-font bg-gray-200">


    <div className=" bg-black h-36 text-xl flex  justify-center items-center  m-20 mr-20 rounded">
         <h1><div className="text-white">STAY UPTO DATE ABOUT OUR LATEST OFFERS</div></h1>
         <div className="ml-36 px-4 py-2 size-2 mb-14 h-7 "><input type="Email" id="Email" placeholder="Enter your Email addess"/></div>

         <div className="flex justify-center items-center bg-white text-gray-400 hover:bg-gray-300  hover:text-black rounded-md mt-14 h-11"><IoIosMail /><button className="flex justify-center items-center">Subscribe to Newsletter</button></div>
      </div>

      <div className="container px-5 py-24 mx-auto">
        <div className="flex flex-wrap md:text-left text-center -mb-10 -mx-4">
          <div className="lg:w-1/6 md:w-1/2 w-full px-4">
            <h1 className="title-font font-medium text-gray-900 justify-betweenml-14 w-{1000px} h-{2431px} top-{-1750px} left-{100px} size-150 gap-{32px} ">
              <b>SHOP.CO</b>
            </h1>
            <br />
            <nav className="list-none mb-10">
              <div className="w-64 h-66 ">We have clothes that suits your style and which you are proud to wear. From women to men.</div>
              <br/>
              <div className="flex">
                <TiSocialTwitter />
                <FaFacebook className="ml-2"/>
                <FaInstagram className="ml-2"/>
                <IoLogoGithub className="ml-2"/>
              </div>
            </nav>
          </div>
          <div className="lg:w-1/6 md:w-1/2 w-full px-4 ml-24">
            <h1 className="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">
              COMPANY
            </h1>
            <br />
            <nav className="list-none mb-10">
              <li>
                <a className="text-gray-600 hover:text-gray-800">About </a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Features </a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Works </a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Career</a>
              </li>
            </nav>
          </div>
          <div className="lg:w-1/6 md:w-1/2 w-full px-4 ml-8">
            <h1 className="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">
              HELP
            </h1>
            <br />
            <nav className="list-none mb-10">
              <li>
                <a className="text-gray-600 hover:text-gray-800">Customer Support</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Delivery Details</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Terms & Conditions</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Privacy Policy</a>
              </li>
            </nav>
          </div>
          <div className="lg:w-1/6 md:w-1/2 w-full px-4 ml-8">
            <h1 className="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">
              FAQ
            </h1>
            <br />
            <nav className="list-none mb-10">
              <li>
                <a className="text-gray-600 hover:text-gray-800">Account</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Manage Deliveries</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Orders</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Payments</a>
              </li>
            </nav>
          </div>
          <div className="lg:w-1/6 md:w-1/2 w-full px-4 ml-8">
            <h1 className="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">
              Resources
            </h1>
            <br />
            <nav className="list-none mb-10">
              <li>
                <a className="text-gray-600 hover:text-gray-800">Free eBooks</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Development Tutorial</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">How to - Blog</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Youtube Playlist</a>
              </li>
            </nav>
          </div>
        </div>
        <br />
        <hr style={{border: '1px solid lightgray', margin: '20px 0' }}/>
        <div>
        Shop.co © 2000-2023, All Rights Reserved
        </div>
      </div>

    </footer>

  </div>
)

