import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}










export function Upper() {
  return (
    <header className="bg-white shadow-md">
      <div className="flex justify-between items-center px-4 py-3 md:px-8">
        <div className="text-xl font-bold text-black">SHOP.CO</div>

        <nav className="hidden md:flex space-x-6">
          <a href="#" className="hover:text-gray-600">Shop</a>
          <a href="#" className="hover:text-gray-600">Sale</a>
          <a href="#" className="hover:text-gray-600">New Arrivals</a>
          <a href="#" className="hover:text-gray-600">Brands</a>
        </nav>

        <div className="flex items-center space-x-4">
          <div className="relative hidden md:flex">
            <input
              type="text"
              placeholder="Search for products..."
              className="border border-gray-300 rounded-full px-3 py-1 w-64 focus:outline-none"
            />
            <IoIosSearch className="absolute right-3 top-2 text-gray-500" />
          </div>
          <FaShoppingCart  className="text-xl text-black hover:text-gray-600"/>
          <MdAccountCircle className="text-2xl text-black hover:text-gray-600" />
        </div>
      </div>

      <div className="flex md:hidden justify-between items-center px-4 py-3 border-t">
        <button className="text-black">Menu</button>
        <IoIosSearch className="text-xl text-black" />
      </div>
    </header>
  );
}




import { BiHorizontalCenter } from "react-icons/bi"
import { FaFacebook, FaInstagram, FaShoppingCart } from "react-icons/fa"
import { IoIosSearch, IoLogoGithub } from "react-icons/io"
import { MdAccountCircle, MdHorizontalSplit } from "react-icons/md"
import { TiSocialTwitter } from "react-icons/ti"
import { IoIosMail } from "react-icons/io";



export const Footer = () => (
  <div>
    <footer className="text-gray-600 body-font bg-gray-200">


    <div className=" bg-black h-36 text-xl flex  justify-center items-center  m-20 mr-20 rounded">
         <h1><div className="text-white">STAY UPTO DATE ABOUT OUR LATEST OFFERS</div></h1>
         <div className="ml-36 px-4 py-2 size-2 mb-14 h-7 "><input type="Email" id="Email" placeholder="Enter your Email addess"/></div>

         <div className="flex justify-center items-center bg-white text-gray-400 hover:bg-gray-300  hover:text-black rounded-md mt-14 h-11"><IoIosMail /><button className="flex justify-center items-center">Subscribe to Newsletter</button></div>
      </div>

      <div className="container px-5 py-24 mx-auto">
        <div className="flex flex-wrap md:text-left text-center -mb-10 -mx-4">
          <div className="lg:w-1/6 md:w-1/2 w-full px-4">
            <h1 className="title-font font-medium text-gray-900 justify-betweenml-14 w-{1000px} h-{2431px} top-{-1750px} left-{100px} size-150 gap-{32px} ">
              <b>SHOP.CO</b>
            </h1>
            <br />
            <nav className="list-none mb-10">
              <div className="w-64 h-66 ">We have clothes that suits your style and which you are proud to wear. From women to men.</div>
              <br/>
              <div className="flex">
                <TiSocialTwitter />
                <FaFacebook className="ml-2"/>
                <FaInstagram className="ml-2"/>
                <IoLogoGithub className="ml-2"/>
              </div>
            </nav>
          </div>
          <div className="lg:w-1/6 md:w-1/2 w-full px-4 ml-24">
            <h1 className="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">
              COMPANY
            </h1>
            <br />
            <nav className="list-none mb-10">
              <li>
                <a className="text-gray-600 hover:text-gray-800">About </a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Features </a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Works </a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Career</a>
              </li>
            </nav>
          </div>
          <div className="lg:w-1/6 md:w-1/2 w-full px-4 ml-8">
            <h1 className="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">
              HELP
            </h1>
            <br />
            <nav className="list-none mb-10">
              <li>
                <a className="text-gray-600 hover:text-gray-800">Customer Support</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Delivery Details</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Terms & Conditions</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Privacy Policy</a>
              </li>
            </nav>
          </div>
          <div className="lg:w-1/6 md:w-1/2 w-full px-4 ml-8">
            <h1 className="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">
              FAQ
            </h1>
            <br />
            <nav className="list-none mb-10">
              <li>
                <a className="text-gray-600 hover:text-gray-800">Account</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Manage Deliveries</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Orders</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Payments</a>
              </li>
            </nav>
          </div>
          <div className="lg:w-1/6 md:w-1/2 w-full px-4 ml-8">
            <h1 className="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">
              Resources
            </h1>
            <br />
            <nav className="list-none mb-10">
              <li>
                <a className="text-gray-600 hover:text-gray-800">Free eBooks</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Development Tutorial</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">How to - Blog</a>
              </li>
              <li>
                <a className="text-gray-600 hover:text-gray-800">Youtube Playlist</a>
              </li>
            </nav>
          </div>
        </div>
        <br />
        <hr style={{border: '1px solid lightgray', margin: '20px 0' }}/>
        <div>
        Shop.co © 2000-2023, All Rights Reserved
        </div>
      </div>

    </footer>

  </div>
)

